name: PR Labeler

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  label:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Add PR Label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ["pr-submitted"]
            });
