name: Static Analysis

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      python: ${{ steps.filter.outputs.python }}
      json: ${{ steps.filter.outputs.json }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Path filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - '**/*.py'
            json:
              - '**/*.json'

  python-lint:
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: action/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff check --output-format=github .

  json-lint:
    needs: changes
    if: ${{ needs.changes.outputs.json == 'true' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependency
        run: npm install -g jsonlint

      - name: Lint JSON files
        run: find . -name "*.json" -not -path "./node_modules/*" | xargs -n 1 jsonlint -q

